
version: '3.9'

services:
  dev:
    image: johnnyhuy/pipeline-toolkit:node-16
    volumes:
      - ./:/opt/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
    build:
      context: .devcontainer
